version: '3'

services:

  beakerbot:
    build: .
    image: ${IMAGE_NAME:-effprime/beakerbot}
    container_name: ${CONTAINER_NAME:-beakerbot}
    restart: always
    volumes:
      - ./db_volume:/beakerbot/db_volume
